### PR TITLE
added readthedocs files and updated content and documentation till date

### PR DESCRIPTION
**Pull request by aniket0112**

### CODE REVIEW

**Comment by ravijain056** [comment]
Tag me using @ravijain056 from next time!

**Comment by ravijain056** [comment]
Add Procedure to get started in the Readme file. @aniket-codedater

**Comment by ravijain056** [comment]
readthedocs didnt get updated.
http://omnidrive-control.readthedocs.io/en/latest/
@aniket-codedater

**Comment by aniket0112** [comment]
@ravijain056 I can see readthedocs right now. It is up to date about the work till June 2016.

**Pull request merged**
